Iter5
mstarodubtsev/go-yandex-shortener pull request #5
Opened 2024-11-14 05:02 UTC by mstarodubtsev

2024-11-14 21:57 UTC, avhitrov requested changes
Data Race condition при организации хранилища. Подробности в комментариях. В остальном на текущем уровне проникновения в Go - приемлемо. Но сразу рекомендую подумать о выделении стораджа в отдельный пакет.

2024-11-14 21:57 UTC, avhitrov commented on internal/app/handler.go
> +var m map[string]string = make(map[string]string)
Мапа – структура потоконебезопасная. Это означает, что в конкурентной среде (а http-сервер априори является конкурентным приложением, так как открывает по горутине на каждый входящий запрос) любые обращения к ней должны оборачиваться блокировками. В Go для этого существуют мьютексы (sync.Mutex или sync.RWMutex). Кроме того, можно использовать потокозащищенные структуры, вроде sync.Map.

Подробнее: https://t.me/bushigo/24

В данном же случае при множестве одновременных запросов имеем:
```
==================
WARNING: DATA RACE
Write at 0x00c00008ab40 by goroutine 7:
  runtime.mapassign_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:203 +0x0
  github.com/mstarodubtsev/go-yandex-shortener/internal/app.PostURLHandler()
      C:/work/src/github.com/mstarodubtsev/go-yandex-shortener/internal/app/handler.go:62 +0x2f2
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Previous read at 0x00c00008ab40 by goroutine 46:
  runtime.mapaccess2_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:108 +0x0
  github.com/mstarodubtsev/go-yandex-shortener/internal/app.GetURLHandler()
      C:/work/src/github.com/mstarodubtsev/go-yandex-shortener/internal/app/handler.go:87 +0x244
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Goroutine 7 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x277
  main.main()
      C:/work/src/github.com/mstarodubtsev/go-yandex-shortener/cmd/shortener/main.go:17 +0x125

Goroutine 46 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x277
  main.main()
      C:/work/src/github.com/mstarodubtsev/go-yandex-shortener/cmd/shortener/main.go:17 +0x125
==================
```

2024-11-15 05:31 UTC, mstarodubtsev commented on internal/app/handler.go
> +var m map[string]string = make(map[string]string)
Вынес сторадж в отдельный пакет, добавил реализацию с использованием Map, с блокировками на чтение/запись данных sync.RWMutex.

2024-11-19 12:54 UTC, mstarodubtsev commented
@avhitrov готово, прошу посмотреть

2024-11-19 22:12 UTC, avhitrov approved these changes
Все ок

2024-11-20 03:57 UTC, merged